// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiMvc.Repository.EFCore;

#nullable disable

namespace WebApiMvc.Repository.Migrations
{
    [DbContext(typeof(WebApiMvcDbContext))]
    partial class WebApiMvcDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("WebApiMvc.Model.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("WebApiMvc.Model.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Contact", (string)null);
                });

            modelBuilder.Entity("WebApiMvc.Model.ContactDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CelPhone")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("cell_phone");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("email");

                    b.Property<string>("Linkedin")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("linkedin");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("ContactDetail", (string)null);
                });

            modelBuilder.Entity("WebApiMvc.Model.Contact", b =>
                {
                    b.HasOne("WebApiMvc.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_Contact_Category");

                    b.OwnsOne("WebApiMvc.Model.ObjectValue.AddressDetail", "Address", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .HasColumnType("varvar(80)")
                                .HasColumnName("address");

                            b1.Property<string>("City")
                                .HasColumnType("varvar(80)")
                                .HasColumnName("city");

                            b1.Property<string>("Neighborhood")
                                .HasColumnType("varvar(80)")
                                .HasColumnName("neighborhood");

                            b1.Property<string>("Number")
                                .HasColumnType("varvar(20)")
                                .HasColumnName("number");

                            b1.Property<string>("State")
                                .HasColumnType("varvar(20)")
                                .HasColumnName("state");

                            b1.Property<string>("ZipCode")
                                .HasColumnType("varvar(20)")
                                .HasColumnName("zip_code");

                            b1.HasKey("ContactId");

                            b1.ToTable("Contact");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApiMvc.Model.ContactDetail", b =>
                {
                    b.HasOne("WebApiMvc.Model.Contact", "Contact")
                        .WithMany("ContactsDetails")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_Contact_ContactsDetails");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("WebApiMvc.Model.Contact", b =>
                {
                    b.Navigation("ContactsDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
